CREATE TABLE "EMPLOYEE_BAK" AS SELECT * FROM "EMPLOYEE";
drop table employee;
CREATE TABLE "EMPLOYEE" AS SELECT * FROM "EMPLOYEE_BAK";

-- DEPARTMENT 테이블 생성
CREATE TABLE "DEPARTMENT"
(
    "DNO"   CHAR(3 BYTE)        PRIMARY KEY,
    "DNAME" VARCHAR2(50 BYTE)   NOT NULL UNIQUE -- 부서 이름은 중복되지 않도록 UNIQUE 제약 조건 추가
);

-- 기존 EMPLOYEE 데이터에서 중복 없는 DNAME을 추출하여 DEPARTMENT 테이블에 삽입
-- DNO를 D01, D02... 형태로 생성
INSERT INTO "DEPARTMENT" ("DNO", "DNAME")
SELECT
    'D' || LPAD(ROW_NUMBER() OVER (ORDER BY "DNAME"), 2, '0'),
    "DNAME"
FROM (SELECT DISTINCT "DNAME" FROM "EMPLOYEE_BAK") -- 백업 테이블에서 고유한 DNAME 추출
ORDER BY "DNAME";

-- DEPARTMENT 테이블 생성 확인
SELECT * FROM "DEPARTMENT";

-- POSITION 테이블 생성
CREATE TABLE "POSITION"
(
    "PNO"   CHAR(3 BYTE)        PRIMARY KEY,
    "PNAME" VARCHAR2(30 BYTE)   NOT NULL UNIQUE -- 직급 이름은 중복되지 않도록 UNIQUE 제약 조건 추가
);

-- 기존 EMPLOYEE 데이터에서 중복 없는 POSITION을 추출하여 POSITION 테이블에 삽입
-- PNO를 P01, P02... 형태로 생성
INSERT INTO "POSITION" ("PNO", "PNAME")
SELECT
    'P' || LPAD(ROW_NUMBER() OVER (ORDER BY "POSITION"), 2, '0'),
    "POSITION"
FROM (SELECT DISTINCT "POSITION" FROM "EMPLOYEE_BAK") -- 백업 테이블에서 고유한 POSITION 추출
ORDER BY "POSITION";

-- POSITION 테이블 생성 확인
SELECT * FROM POSITION;

-- DNO 컬럼 추가
ALTER TABLE "EMPLOYEE" ADD ("DNO" CHAR(3 BYTE));

-- PNO 컬럼 추가
ALTER TABLE "EMPLOYEE" ADD ("PNO" CHAR(3 BYTE));

-- DNO 업데이트
UPDATE "EMPLOYEE" E
SET "DNO" = (SELECT D."DNO" FROM "DEPARTMENT" D WHERE D."DNAME" = E."DNAME");

-- PNO 업데이트
UPDATE "EMPLOYEE" E
SET "PNO" = (SELECT P."PNO" FROM "POSITION" P WHERE P."PNAME" = E."POSITION");

-- 업데이트 결과 확인 (선택 사항)
SELECT ENO, DNAME, DNO, POSITION, PNO FROM "EMPLOYEE" WHERE DNO IS NULL OR PNO IS NULL;
-- 이 쿼리 결과가 비어 있어야 합니다. 만약 NULL이 있다면, DEPARTMENT나 POSITION 테이블의 데이터가 잘못되었거나, 기존 EMPLOYEE 테이블의 DNAME/POSITION에 오타가 있었을 가능성이 있습니다.


-- DNAME과 POSITION 컬럼 제거
ALTER TABLE "EMPLOYEE" DROP COLUMN "DNAME";
ALTER TABLE "EMPLOYEE" DROP COLUMN "POSITION";

-- ENO를 기본 키로 설정
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY ("ENO");

-- DNO와 PNO에 NOT NULL 제약 조건 추가
ALTER TABLE "EMPLOYEE" MODIFY ("DNO" NOT NULL);
ALTER TABLE "EMPLOYEE" MODIFY ("PNO" NOT NULL);

-- 외래 키 제약 조건 추가
ALTER TABLE "EMPLOYEE"
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
FOREIGN KEY ("DNO") REFERENCES "DEPARTMENT" ("DNO");

ALTER TABLE "EMPLOYEE"
ADD CONSTRAINT FK_EMPLOYEE_POSITION
FOREIGN KEY ("PNO") REFERENCES "POSITION" ("PNO");

select * from employee;
